controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_post_delete:
    path: '/delete/{id}'
    controller: 'App\Controller\PostController::delete'